### PR TITLE
use Object.keys instead

### LINKED ISSUE #55: Octocat and ember extending prototype
I have use the latest ember cli (1.13.6) to generate a default project.

Seems ember are extending array prototype. (which probably is a bad idea on their part anyway)

In my ember route I do the following:

` return octo.users('mokkabonna').repos.fetch({per_page:1})`

The code trips out here with maximum callstack error:
https://github.com/philschatz/octokat.js/blob/master/src/replacer.coffee#L59

In particular it seems when octokat encounters a key named " super" (notice the leading space)

Sure it shouldn't be if typeof value instead of key? Isn't key always a string? If i change it to that it seems fine.

Anyway isn't it better to use `Object.keys`? Or if you want to support es3, use at least use this:

```javascript
for (var name in buz) {
  if (buz.hasOwnProperty(name)) {
    console.log('this is fog (' + name + ') for sure. Value: ' + buz[name]);
  }
}
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty

### PR DESCRIPTION
**Pull request by philschatz**
use `for i in Object.keys(obj)` instead of naively using `for i, val of obj`

Fixes #55

### CODE REVIEW

File: src/replacer.coffee [hunk 1]
```diff
@@ -55,7 +58,8 @@ class Replacer
   _replaceArray: (orig) ->
     arr = (@replace(item) for item in orig)
     # Convert the nextPage methods for paged results
-    for key, value of orig
+    for key in Object.keys(orig)
+      value = orig[key]
       @_replaceKeyValue(arr, key, value) if typeof key is 'string'
```
Comment (mokkabonna) [inline src/replacer.coffee]: I would still say that this line make no sense. Key is always a string. You resolve the issue of #55 because you only iterate over it's own properties, but it still call replaceKeyValue for ALL properties.

Comment (philschatz) [inline src/replacer.coffee]: Thanks for catching the type check!

`_replaceKeyValue` recursively goes through the values and converts them. So, in the case of  the value being an array or object, it will continue converting them (for example the `owner` key/value when retrieving a repository).
